services:
  postgres:
    image: postgres:16-alpine
    container_name: the_reach_db
    environment:
      POSTGRES_USER: reach
      POSTGRES_PASSWORD: reach
      POSTGRES_DB: the_reach
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
